
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from miniogl.rotatable.VShapes import VBasicDetails
from miniogl.rotatable.VShapes import VRectangle
from miniogl.rotatable.VShapes import VRectangleDetails


class TestVShapes(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 26 June 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testVRectangleScale(self):

        vRectangleDetails: VRectangleDetails = VRectangleDetails(x=10, y=10, width=100, height=50)
        vRectangle:        VRectangle        = VRectangle(vRectangleDetails=vRectangleDetails)

        scaledDetails: VBasicDetails = vRectangle.scale(factor=2)

        self.logger.info(f'{scaledDetails=}')

        self.assertEqual(20, scaledDetails.x, 'x not correctly scaled')
        self.assertEqual(20, scaledDetails.y, 'y not correctly scaled')
        self.assertEqual(200, scaledDetails.width,  'width not correctly scaled')
        self.assertEqual(100, scaledDetails.height, 'height not correctly scaled')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestVShapes))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
