#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAE4klEQVR4nO1WbUxTVxg++0yWuB/bQuKv/XSgosg0my5sQdrb8iHjQzPjwuK2bC6azWEC'
    b'tl0LVSBgQWWAoJkMAfkqH2W6oXwoIGNbcKKbozOILGgH1lLuObc/tizbnuXc2AulgjCFZMme'
    b'5P1zc+77vM/znvOeQ8j/+C8BwKOMsfWMsX2SJJUzxtrdbveFiYmJesZYNmMs2uVyPb0QxE9J'
    b'krSXUnpbkiTwGB9349rPv2Do+k04nePyNx6U0t9GR0erRVFc81DIKaUaxtgtnvzypWvIzq5G'
    b'bKwJ6ogUaOPSoI1Pg1rQISbGAJ3hODpa+0Ap44X8PTIywp1Zxl2jlD4zb3LG2MeMsT+Hb9zC'
    b'npSjEGI+wYvGUqw40YIXmrt9IqiqFSEZFVAnZSM+Ph22hm4wxhRnRFH8fXBwMHXO5JIkpfIf'
    b'+777CdHRBqw1liKwsdOP+F6x8ugXUG3Lwo4PDsuOGE1l+L7PLhfS399/eC7KNzHG/vr2mx+h'
    b'idQjuKjRl6SpEyuLbQjJKMeafSew6rAVQTXtvmtsXViXXgZtohmhhs+g0erB8/EiWltbk2ck'
    b'dzqdSxhjozeGbiIqyoDgI01K0sD6c3h57zG5qO3v5sG8vwL7MyqxY+enECJSoXrb4l+s15Vi'
    b'G7SRelwfHMHw8PAwIeTZmdTzI4bdyUewNu1zJcHyyrNQJ6Qj3VyOmyOjSm+9MeEWcaq5B3EJ'
    b'Zry6Mx+Bti7fPVLbDk2sCRf7BuBwOMYIIcF+5AAep5TeuXTRDk2sUbZaVm49ByHejOqT7X7E'
    b'04PbrNqYIrvF90xQVZtMrtpsRklJs7ympaWlmRCyzK8ASqmaL8jMqkSoqVSpfsOeYmRlnbwv'
    b'OS+c2xxc2CD/t+L4aYSp90L1ukkhHxgYuBIQEJBACHniXvZn8kUxMUYsv3vUAhvOQxB0GP3V'
    b'OXfypk4E1XXIyiNijbAcqJbX2O32H5YuXbqFELJkpv7Xue64oVanKupXHbJi1+6ieSkPLrEh'
    b'TKuDKj5NUT6FfOZRTSntuWYfhjbBrBQQml6G/PyGGcn5+Z6qPNB6Xla+MdoAi6VGsX1W5V64'
    b'3e5uuYDEyQLWmEpRVGi7JzkfzZH8qBbcVV7QiLBoA1SJZhQXKz2/v3IvRFFscdy6DSFSrxSw'
    b'OqcaemPprMrlI8f7znseZUBebu105XO7ISmluXx+awQdAmvblfO/KdbkM9d9bOdFHqzFK3Em'
    b'qBImez5F+ey2T4XH49nKf/4ouRirD1QrLmi2ZeLrniu+5AWNsnIesvJIHQ7m/UvlXjDGnqOU'
    b'/tHU0IXw9/Im22CpwVvbLfIU85Lz7yE5VdiwZR9UiekPpnwqxsbGzvLHRqRWj+UVZ5QiIpKy'
    b'oY5IVcjl8VrTho1arrxu/htuJoyPjws82bFjp/Da+4d8LiI+VmXlGeVY/2bWdOWXH0j5VDgc'
    b'jh5RpHhjayZW59b4Pz5qOxAh6JB30PpwbJ8Ol8sVzhM3N3ZDk5TjM5ReescC1eYFUu6FJEnx'
    b'PPmuDwtlu5UruaoN4UIq8vPrF46cw+PxBHOCL0/3QuAXU8UZvyt1wci9GBoaquREjfWd8mNU'
    b'SFhEcg4Aj1y9erXJ+zC90NW/MBtuNlit1sd6e3uPOp1O0eVyeTo6Or4KCAhIXBRy4ovnCSHr'
    b'CCErCCFPLjb5guIfQ+WaFaXgcOwAAAAASUVORK5CYII=')

