#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAGLElEQVR4nO1be4iUVRS/mr3fZU8qiorCCiuVzNzv3NnWUDCiTIzoQQ96KBkVGL2oP7SH'
    b'lT0pygoKjNSksDItbHbnnJnVbakoi4IMFHwVpeWGVuQvzuysjXfuNzq733dn1vrBx4h+3t+9'
    b'5zvn3HPOPdeY/1F/UBaDKIexxHjIMl4jwRxiPGNzmJwRnGx2V9AyHGcZz1rBj1aA2IfxlWVc'
    b'a4CBZnfA2EXYmxj3kKCr6sKdhxjLqYBTTH9Gi+BYy+ioZeHOszGTR2T6I0gwnBhr+rD4bk0Q'
    b'dGXyGGUaHRPnYY+eP2cYw4ixqYp6/2oZBRIssIwcMX7fiSDWNrXhGNPIoDzO1N/mHIZYwU8x'
    b'Dq4jYlyqfqH8/45Zgv1JcIcVbK4ihPdMoyISZKgdJ1IWg61gtWfyWyzj5p159qiAs6xgXRUh'
    b'XGIaDaMEB1rBw7o4YizxqW+Ux4hdHc/mcB4x/ojxB18YYIBpJJDgCbV5K3jQY+sbKI/Tax6T'
    b'MSNOCyLGONMoaM5hCAlaSXC2FfxV4b0ZQ3urVcT4OUYLFphGgRUsyjCuIUGnO9EM48o+jc2Y'
    b'GSOAraMZhya3il7C5nCBbnXEuN/j7WebPoIYI6vEBleZesMyPiHG21bwi+v0EvlCwEAdK0YA'
    b'r5p6IhKcX5pIhepbwYSkeCzj5dKY7tb4g6knSDC36PQYfzpfRpLk0dihNO7cCi3IYrCpB5ra'
    b'cLzr8bc7voRj9kjQVPIpUyr4ciBTD1jBvTHO6eOkuS5cjsN7zKqijsCYYuoBEqyISXBaUuFj'
    b'rKc8LifGYkcAs0xoZBhDY0PUlKBjqwCs4BGH9820OGNBjMe86p/DZJMSNF3WJIgEtzi8WRMU'
    b'KO7LFZme5vItnTg4LVpNg7UqRDmMd0zgGxMSUR4jYmz/rTR5tWqsaXKUxzmO2a0yIWEF02K8'
    b'/4RUeRkvakW5hXGCI/j1afJWwAo+9Di/rvGd2M+kLADlGJ3DEY4ANplQGNaJPX3lKmK8nzY3'
    b'CZ4u/mZxgMO/xYTM/KxP/fOYmjq34M6eomvdNMAy7vKGvowzUucu+Rg9UnOzThMKJHjdI4CN'
    b'IepzWm7T37HLcJCjAd+bULCMzzz2vyQEd4+TLSVh5Q64M9xprmCrRwDTg0wgpkJEjHeDEGcE'
    b'p8XYf59qfrXCCiY5GvB8EGJitPgE0NyGc01AeJKhaUGIKY/rfALQ0rUJCCv4qC7nA8R4oEIA'
    b'jN9MSAAD3HMCPXoPwm0Zszwh8HcmIJracJLjADcEI7f/VmbLNaAQbALdcYhbC3gnJPkczxa4'
    b'NNgEus1wqaOBtwUjt4J5HgF8EIp/TB5HulXoECF4VQ3QM0ETCJoMVRRCQh6Rk+AVjxNsDcj/'
    b'tcP/uAkJ293b5zrBT0Nway3Q5a6l2SIRkOBRjwCCFCS1IOr4nm+Dd4jYPKZ6fMC68ne0Pyhp'
    b'3mLTBWObI/jbTWhEjIs9GrBNS1Rl74y7qIDDkuS1jPmO3+miLA4xoRF1d25VTYY0Vc0wbkqK'
    b'kxijK76+4Lmkxq8JxWJk5WT0mdTzTnM7jtLeXpMAirU/xucO15Zgsb8P6vQ8ZjBzh3cE6yLG'
    b'GNNHqJ17hP2UqSdI8JJHAF9W2CyjQytIfeAZ7lafNAvUM4FEFtJbaFOSzw9onW77O3lcUfr7'
    b'+3rDoX1F2vriciTpW3qNYkHS5wfKtiXKYh8tVWuXp7bO1twI4W+rb2+YixNW0O4JiVfpqVHP'
    b'OyS4tfRvm3e1YqPOzdd0oR3lDXVhwuYw2WcGWjJzjtCLpSti/K1htO4Qcd6ecrg67gpN6KLr'
    b'TlE6m3N7AnWha8qDIA1WdEss0xJ1agst427tKs0wrifGkyRY6Vt4Q3j9muqD3UJYXO799TBD'
    b's7a4brJqT7EXuFHs3oUuTO0+ZvILy8Pj7c3UeiWu+h2AHQQ5soB9TSODGLZo3/6vtzLDuMz3'
    b'BXUnKeYVjIJXAIz5E1dgL9MfYGNOi8ue1Ro8ae1O4wMS3GgZL3hb4DWxYswov3PUL0DaJe7P'
    b'EWp51jbUBYha4e3g3DVHt1Vb7kKfLqWC0rY3Pa613Q2cVHMoi6PN7gbKYpC20ev1N+3rsYI3'
    b'tK+/eP+HcUPUilPrPUfzX8c/Redr/v6QExgAAAAASUVORK5CYII=')

