#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAABaUlEQVR4nO2Wu0oDQRSGv1aIVmqRBLzU2sTSTvcBJA9gKepDaKEIXl7A3lhYi/ESK00f'
    b'n0E7tfCKCiYy8C8MSzZkd3YVYT6YZs515+ycM+DxeP4JBSAA1oE6cAPcAe9at9qrSyeQjTMz'
    b'wD7wBnQSrg/gSMkkZhw4t5x9A1fANrAATAFFYECrqD0j2wGuZRPan8lnXywCLzK8BzaAsZQf'
    b'sSkfHfk0vnuyDLRlcAAM484IUJPPtmLE1vtLRxer5MCKEjAxKt0ULpWlqXNe7CpGIyooK7sn'
    b'YDDHBIzvZ8Uq2YJAmV2QP+FJB90SaPxVAuVfKsFQXAnszEwjyYu9Xiddsa6huTJZs6ov/4y7'
    b'hoYlqxHV1ERcGQUOrUZkYvTdih+ALWAiReBJ2T4macUhpvefRoZRUzWsAtP6icJhVNJeVTrN'
    b'yDA6STlPCMfxq8M4niUDCsA8sAYcAy09QuwHSUsyozOX1YPE4/GQNz89vYaoQCqyqQAAAABJ'
    b'RU5ErkJggg==')

