#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAAcklEQVR4nO2WoQ3AMBADj5S0IHqQOTJDcHFxl+iK3askIKD4DeKTgk+vWJbBLEQBNpU8'
    b'gBfowKGSn0AbTyK/gaqSP5niv8sl8mv8d1XJqzJwzWnPIpx2nPZEwt2Ouz2RWHbJFGW3M3Z7'
    b'VyyZmT17TBiUfGqpIzY2yhqPAAAAAElFTkSuQmCC')

