#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAA2klEQVR4nO3asW3DQBBEUVZndcIWWIADshWF6sCZ3IIhCG5hAOcagYEDC3DkwIDufWAL'
    b'uAV5tzsz0wQAAIbmZX2fD9u5I9V+5umxAcvxo6+n61PXfsZfG/B2+epnbk9d+xk1YPMF1C+w'
    b'ugNml+A3XoHVMzibAzaDUE2CF6Nw/3tWtwvEMlTbYKzDpQeEIFKKUEhipQmGKFqqcMji5QuE'
    b'MVLOUFhj5Q2GOVrucNjjlQ+IgEQlRCIiUxmhCElVSixicpUTjKBkJUXzx6jsMnpY+jBQ/WgA'
    b'AACYRuQOPUYK006tmFcAAAAASUVORK5CYII=')

