#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAD3ElEQVR4nO2T21MadxTH+Rsc18hFVlnuC8tdQFMTb0RXFJEWdbTPrRnbP6IPnabtg8lL'
    b'pp0+9bEvqa2T/heZmJFlwYUFAUODsctFnCTC6Rx6eTPc8uh35szs7J7P55zdH8hkN7lJF6lt'
    b'heWXn0Y+r29HDupbEa6+HanWtyK1+naEr29F/rjc/mS3vr4+IvvQqWwGBy82Vr+52Fx9U98M'
    b'w/vqYmO1Ud8I/3K5Hhr9IMNr68HFWnRZqkVXoFUbayBFVuCMDUBxfqZVeI338Nn/fdHlykU0'
    b'tNzfm38c/KyytnRVjQShFg1DaXEeRKe9KTpsuYzH/eTE59nDynidv6YdTB6fYQ/2IlNZW2pU'
    b'w+wXPQ2XwuyCFFq4Kq8uwl+rQch4PZB22p+JEx77dUze73aknLbn2IsMslJooVEOLXT3JWos'
    b'OywFA5K0HIDzFRZSdqaR8Tq+7pTPup0PkEEWHdLyfLm0MqfoeIFzdvbxOTsLUogFcdwFotv+'
    b'oKs3aC3h+ApZdKDrnJ35sSOwNDenOLs3/fb1vWkozt6FlM3yTNZjBIY+RAe6zgJ3r84W7qg6'
    b'WODOTmluCl6zARAYS1O02a4983bJOq0uwWppogudpdmp+22hP6cnD15NT8KrwAwItCkn6zNJ'
    b's6mALnSiuy1QnPLxxSk/nE7dBsFKP+l3AYGh99GFzuJHvnhb4HTSU3k5OQ45vxdSFvNevwuk'
    b'rPQjdKHzdMJTbQvkx13VgtcFJ75xOKaND/tdQKBNj9CFzrzXWW4L5Fz2RN5th7zfB0mjoe8j'
    b'SJr0++hCZ85ta38EWQfz9MTBQOH2BCT12ny/CyR02gK60Hlit/7eFshYzLtZhoaC3wtJg6Ep'
    b'mkyOXofzer0HHehCZ5ahd9pCSatWlTYbr0TaCFmPG+KU5nmvCyQo6gU60CWaDe9ObDplR2Da'
    b'oPspbdRDzu2CJG0GnqK+7XY4r9V+J9DmlgNdKaP+ccdw3GBQCFpNVdBRkHU7gdfpGvzYWMdL'
    b'8BrN98ggi45jHSVljGp5V29wTI2GkprRxrFmFDJOOyRMRoiR5KFAUa5rB4+NefhR8sWxydhi'
    b'kEVHQqNekvWShFr9JU+ONBLkCIhWC6RtDPBaqnlEkgWOVO9zJLnHk+RDjlT/FiPJAq/VNrEH'
    b'e5FpsWrVrqyfxEcUK7xKWeFVSsBK02YQbTZIM1YQLJZW4XXrHv5e/u2LK5VlTqEI9jX8vyRU'
    b'KmVMfusHTj78jpMPw/sqJh9ucPJbP3ODg92deSc5HBhQcQRx/2iIeBobIuJHQ0QlRgzWYgTB'
    b'HQ0RBzGC2EkMDHT2V7vJTWT/5G/w/EUra89L/AAAAABJRU5ErkJggg==')

