#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAF3ElEQVR4nO2ba2xURRTHf1QKVR4iDwGViAVRgSIEKCItKLsQX0iVR1ssiCjQgg0UrQYs'
    b'tvJqu71TW+URxEjUiAkBRQQRhd0PfkGj+MFoghKNCY8QURCEqjzWzNwBy+69Ze3u3V3c/SUn'
    b'2XTvzsz535kzr1NIkiRJkiThM8bLiFE+2pKITNpIK5eX79w+CklEXD4Wu3343T6+xU8LEol7'
    b'd9PL7eW0FsDv9jIq6CEP3TDIQVCJYBeCbxAcxOA0gr8Q/IZgH4KPEdQhyKOOrlwJuH1su+i8'
    b'D7/Ly0b1xct0QDATwWcYnEfg/08mf2PwOYKneZVOxCMuL7mNndcCnG2zmrX67fojZH8gqKWa'
    b'G4gX7vuI9m4fBwIFkJb+bsQcD+wVJxGUspbUWPuP28srVs5LG/kp/pRah0QwbS/V3Boz58d6'
    b'GezycdZOAGnd1ls0vIrjLOJLiniPJ3iLPFYzmZVM5XXm8D4L2UOVCoihiHBCBdZoU15OisvH'
    b'nqaclzZkm25oJb8yl60M5jkgPyQbQqkSRP626SFxFoNZURXA5aP4cs5fsM6L+IA0Cho5lwc8'
    b'AAwHBgP9gX7AQOBuGVr0M+bzaUzlMV67bK+IlgijfHRzezkWqgDD1uEFcoEs4CYIKXjJZ27U'
    b'gkxWQnRmBiXstJ1OZU+oZbzjAri8zBq9iyOhCuDaTcNQuQhqPmnAnReFyKEWDw02IvyOoDcO'
    b'kwrkdMhgzu0l1GWuYUf2Jva5dnPGVggvz0SgXrnJukeJkE0ZVWo6tJ4dHJ4ib7tkjGpr3YXp'
    b'N+dTMaiKDSPeYe/onZxsJMJ+GTgjVP8dqv4sXmiiJzyLw7QEugB9gZHAo4GCpKQwpesYSvsv'
    b'Zt3ILWwa41NBLlL0UENCDgermCAXS7V0J8q0BW4Bhuoo31iQ+x2oTwbJPObzic1QEMSY1rqR'
    b'MoC5gOscqKOPmh0qOWazd+hIApBFAetsYsFcEoA02pBvuWI02EOC0Je5bLEQ4PwVc6gSJqlk'
    b'UmI5DGrVAioBaMkQy2DooZ4EoRML+SJIgEq1F0kIWlDM5iABqvmZhKFQLX8Ch8BxEoZCyoIE'
    b'qOHv8AsW6tw+MMLKQ474Yh6lzghgcNRieom/K7DnLXpAFSfCL3gFh4IKrojD6eVFVgW1czmH'
    b'wy94MXuDCl7GDuKNZewMamcZX4Vf8AK2WkTXI8QT8kLWwy9B7VzAlvALn8YSm2WmPM2NDwQZ'
    b'lm2cSkX4hfdjrM3Jy1LiBfPWOXgzlIE7EsWnU8F+iwoOUE4rYk09rTEsAnU53+tTqrC5hums'
    b'tzl0eIpYI5ht2bbHeUO1PSL0JBcPf1pUdJBq2hErqrgWwWGLIN1Aj8huhfsyj+2WSgtWEisM'
    b'1li2qZgP9RF6xLiadAotz+LNAPkI0UYwydJ52caezFZtjjDDeJINNrHgFIa6y4sOgkx98hvc'
    b'lhm8DWQ6UW070pjCEn6yEeEoNQzDaQR3Ydhcm7/Ej6QyRd9TOMJAMiixvZYy38oEpyqnhom2'
    b'b97DKfoxHxjg9LXYOMYjMDhnI4LsDauop31Eo71dwDPrO8fD1AAPAVfhMB3Vnb/dhUTjKVIm'
    b'LoSzWJKLHLn1tprqGgdhmURh5iFE7Taot7r3kyI01RMurBgFy9V6PVQ8DMBghRKx6bLPaefl'
    b'HWQvokyGTlowqA4xJ9Bcsm5WzplvtkCZ/Gw6vLnJtx045s1un69TbWLCANUAGRjtZgcnTEZ7'
    b'M+BJ50PvWQ7RR11Vp1LAdN4MuTc0x+RyvIhNKnnKHPOxyxUMQAafceqNpFNEMdtt9g7NdbxB'
    b'LW9vpki/9fE6SSOuSNWpb2YKTXdmMo31VPBDs5Ol5ZZW7uquV7vOC2l2w3X+QdzSQafF/ZtL'
    b'1IPZTKRe9YwyvmYph1Sik8EZZfKz/Jv8Tj4zgTr1m0vzC7N02VcM7YFBMqss5AzRYMvRZURu'
    b'URUDWqjLSzOpKht4UAewQGdz9XfZ+lkZV/7X/32Sqk9spMU+/T1JkiRJSED+Aadn1/O5WDvH'
    b'AAAAAElFTkSuQmCC')

