#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/ogl/pyenv-3.11.5/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAF30lEQVR4nO2ae2zTVRTHPwMGk4fiUMAgkYeCCkMEeajMEdoZoiLIYwMcCIrAEAISVIg8'
    b'Jq9t7e8OJihBDERN+ENAdIoCQmv4i6io0b9Ao3/II4RHggLD4Ki5t3c42/vrytpf27l+k5M0'
    b'7a/n3O8593fu4xxII4000kij8SDPT9t8H4/SVOH2U+z2c3Tk57SiKcLt40e3n4DLz1IaDdbT'
    b'CcFEBOsR7EVwFMF5BH9hcRnBCQQ/ITiAoJQKRuOhc6gal5/hkrx2wBXXl/QiZWFxGxbzEHyN'
    b'IHDDYnENi0NYzKCMW6RKt48dtQ7QTthHykHQRUXa4lKDiJudcbnNRja5D3K1rgOUHKSAlMBm'
    b'MrFYjOBi3IjXkZ7bQ4jXio9TeX7aJ5f8Onpj8YMTxKU0qyDw2H4bBwSlMnnkvYxF8EdUZMo4'
    b'z2scZg67KWILBWxkIm8znfcp5iOWcIQyLoT+r/PWiOQDLh81+T6GJJ68YBYWf0ckXco5RW4A'
    b'i4BJUclAXmUuVcphgsCgzyI7QCfEbyd8SPPEkhf1EJ/MZrKYUofcRGAk8AjQH+gD9AUG6u+e'
    b'0M8En8+iKHsJn9RHvo7MTdy0t2wiL5evBewlm+maSIEm1wVoEYX2TOBOYBhQOPRd/NE6wOXn'
    b'wogDyo7DCU/YvPMeqhmDpYlPAPoBWQ01NchDZ9dBqqN1wIgDnHb5mIljWEFL22xfxp8M43VN'
    b'Pg9oE6s5t59FkRJfXhXHh27jUN9lbOmUzys0ZyzQEsdgqXXeFPkrDGe5fn/vjYutABkuH8eu'
    b'E95Pde5Ojg58k6pec/C27c4MQwKV9nvj4A7vovGdD077Av3uxgX5fvrn7mZXbXSbNWOygfB4'
    b'OVGAB3SOcTT664zRlwkv6PmuDlgdGUJ4DKi7ABnlbCCDhGADHYx7e7nUBbP9PQ5YvVUeAOtE'
    b'N4nnf0ud6sKjL9f54HL1P4fFN4bonyWLwliWucYBLx1Vogt1gNzexivjpzSEuskJn/4PMT/K'
    b'nV0jh4cNxuQHA2gSKOWrMAcs4bBehpoAyvk9zAEvsSNxa3CyUR5+QcFsBE0GFlcNK4A89DRh'
    b'ByxQtzupBS9TDOeUK7ErLjOc/Ren4AywKDYs12diV7yGU2GKl7OBVEOJYbley4nYFS/juzDF'
    b'q/mCVMNq9oWNcylHYle8kCrDBchpUgkBMvBwJmycC/k4duVTWWncCleoG93UgCDHOMYplMSu'
    b'vA+PGw9DFqtIFciKsummKkfdFsWMHpTwi8HAcXVJmmxU0gqLk2HjW8ExoHs8TLRmGtuMU0yW'
    b'rpMNuwLNc2xVY48LulGobn7DDZ2gnHYkC7JvQBiWaVmf6Brfsvn9zGeP0dOCjSQLFpuMY5rH'
    b'p8B98TR1Ez2YrTxrSjaCZ0g0BBOM5OUYuzFLjTnOGMILbLfJBZewVP0vMRAMtm3EeJ4PgMFO'
    b'mG1HFpNZyW82TjiLNwE1esFQLM4Zx/AGv5KpCihtnTLfnxxeNr4KQZFRGeeUcbyMt428h0v0'
    b'YYEuyDqGFsAoRiOwqLFxgpwNb1HJzXHN9nYJL2ivhqfxAk+B800S2bJur1pc7AZUu0RazIxp'
    b'syQ3ORXq/il8qaubhJ/lHTWmBN5T3q1qddIJkWZC7Y5RsEbt16OFh35YrNUNlJF012jysm7Y'
    b'kwQjRxmWleFy1e0ZaTbUDlhuWXcpcsHIFimRn4OEd0WMdug7H5z2k3SbTVLQTw1AJka71cEJ'
    b'kdk+mPAk+ehnlkPopcrjmRQxjfeing0NEbkdL2anbrwqdKgq3SDI5DNKRaQHxcxjj83ZoaHE'
    b'q9X29i6KddRHA7eTYsjU7W7BNrc7eJGpbKOEn433CfXni2vqSCtPdR2vt8NI3Q8nt1egfrTX'
    b'PQP/9vt1ZRbjqVQzYynfs4qTqqlKXrlLkZ/ld/I3+cw41qv//Lf3R+pMck/wjUFuhB7UbS2T'
    b'GihjtI74baqSgAyggzpSQy7wpE5goWQL9W+5+tkE9gAlL2e01iI/p5FGGmmkQYLxDwHS1+g5'
    b'b1TtAAAAAElFTkSuQmCC')

