
 os: osx

 osx_image: xcode13.4

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

#dist: bionic

#language: python

cache: pip

#services:
#  - xvfb

#python:
#  - "3.10.0"

before_install:
  - brew list
  - brew upgrade python
  - brew install pip
  #  - sudo apt install libgtk-3-dev
#  - sudo apt-get install python-wxgtk3.0
#  - sudo apt-get install -y  libsdl2-dev

# command to install dependencies
install:
  - python3 --version
  - pip install Deprecated
  - pip install html-testRunner
  - pip install pyutmodel
  - pip install wxPython~=4.2.0
#  - pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
