from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from miniogl.Shape import Shape


# import the class you want to test here
# from org.pyut.template import template


class TestShape(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 22 June 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testIDGeneration(self):

        shape1: Shape = Shape()
        shape2: Shape = Shape()

        self.assertNotEqual(shape1.id, shape2.id, 'IDs should be different')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestShape))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
